ProxyEndpointConnectException: new exception for connection issues to endpoint HTTPProxyHTTPConnectionImpl/SocksHTTPconnection: updated to support new exceptions SocketConnection: added two new protected EndpointConnectException/InvalidAuthException exceptions DirectSocketConnection/HTTPProxySocketConnection/Socks4SocketConnection/Socks5SocketConnection: updated to support new exceptions